#!/bin/bash
NAME=keycloak
IMAGE=yayingongyu/keycloak:latest-r1
MEMORY=512m
LISTEN_IP=0.0.0.0
DOMAIN_NAME=luotianyi.dev
SNI_FQDN=auth.luotianyi.dev
DB_HOST=host
DB_NAME=keycloak
DB_USER=keycloak
DB_PASS=keycloak

function start() {
	docker run -d \
		-m $MEMORY \
		-p "$LISTEN_IP:8080:8080" \
		-p "$LISTEN_IP:8443:8443" \
		--name $NAME \
		--restart=always \
		-e KC_DB=mariadb \
		-e KC_DB_URL=jdbc:mariadb://$DB_HOST/$DB_NAME \
		-e KC_DB_USERNAME=$DB_USER \
		-e KC_DB_PASSWORD=$DB_PASS \
		-e KC_HOSTNAME=$SNI_FQDN \
		-e KC_LOG_CONSOLE_COLOR=true \
		$IMAGE start --optimized --proxy edge
}

function stop() {
	docker stop $NAME
	docker rm $NAME
}

function restart() {
	stop
	start
}

function update() {
	stop
	docker image rm $IMAGE
	start
}

action=$1
if [ "$action" = "start" ]; then
	start
	exit 0
elif [ "$action" = "stop" ]; then
	stop
	exit 0
elif [ "$action" = "restart" ]; then
	restart
	exit 0
elif [ "$action" = "update" ]; then
	update
	exit 0
else
	echo "usage: $0 <start|stop|restart|update>"
fi
